#ifndef LWIP_SOCKET_EXAMPLES_H
#define LWIP_SOCKET_EXAMPLES_H

#define SOCKET_EXAMPLES_RUN_PARALLEL      1
#define SOCK_TARGET_HOST4                 "192.168.10.16"
#define SOCK_TARGET_PORT                  8080

#if SOCKET_EXAMPLES_RUN_PARALLEL
#define SOCKET_EXAMPLE1_THREAD_STACK_SIZE (512 * 2)
#define SOCKET_EXAMPLE2_THREAD_STACK_SIZE (512 * 4)
#define SOCKET_EXAMPLE3_THREAD_STACK_SIZE (512 * 2)
#else
#define SOCKET_EXAMPLE_THREAD_STACK_SIZE  (512 * 5)
#endif
#define SOCKET_EXAMPLE_THREAD_PRIO        (56 - 17)
#define SOCKET_WAITER_THREAD_STACK_SIZE   768
#define SOCKET_WAITER_THREAD_PRIO         (56 - 18)

void socket_examples_init(void);

#endif /* LWIP_SOCKET_EXAMPLES_H */
